name: Warnings Tests
on: [push]


jobs:
  tests:
    name: With Warnings
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.11"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: withfftw
          environment-file: .github/fftw-env.yaml

      - name: Install Test Deps
        shell: bash -el {0}
        run: |
          which pip
          python --version
          pip install .[tests,fftw]

      - name: Run Tests
        shell: bash -el {0}
        run: |
          python -m pytest -W error

      - uses: codecov/codecov-action@v2
        if: success()
        with:
          file: ./coverage.xml #optional
